sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

script:
  - bash scripts/build.sh $TRAVIS_BRANCH
  - docker swarm init
  - docker network create --attachable --driver overlay redis
  - bash scripts/bootstrap.sh $TRAVIS_BRANCH
  - bash scripts/test_init.sh $TRAVIS_BRANCH
  - bash scripts/test_scale.sh $TRAVIS_BRANCH

after_script:
  - docker network rm redis
  - bash scripts/cleanup.sh $TRAVIS_BRANCH

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      LOOK_VERSION=$(cat redis-look/VERSION)
      SENTINEL_VERSION=$(cat redis-sentinel/VERSION)
      UTILS_VERSION=$(cat redis-utils/VERSION)

      docker tag redis-look:master thomasjpfan/redis-look:$LOOK_VERSION
      docker tag redis-sentinel:master thomasjpfan/redis-sentinel:$SENTINEL_VERSION
      docker tag redis-utils:master thomasjpfan/redis-utils:$UTILS_VERSION

      docker push thomasjpfan/redis-look:$LOOK_VERSION
      docker push thomasjpfan/redis-sentinel:$SENTINEL_VERSION
      docker push thomasjpfan/redis-utils:$UTILS_VERSION

    fi
